version: '3.9'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_DB: 'linda'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
    driver: local